#!/usr/bin/env sh

. /etc/opt/sonoshttpapi/sonoshttpapi.conf

# Directories
CONFIG_DIR=/etc/opt/sonoshttpapi
VAR_DIR=/var/opt/sonoshttpapi

CACHE_DIR=${VAR_DIR}/cache
WEBROOT_DIR=/opt/sonoshttpapi/static
PRESET_DIR=${CONFIG_DIR}/presets

# Generate settings.json
jq --null-input \
--arg ip "${IP}" \
--arg port ${PORT} \
--arg securePort ${SECURE_PORT} \
--arg cacheDir "${CACHE_DIR}" \
--arg webroot "${WEBROOT_DIR}" \
--arg presetDir "${PRESET_DIR}" \
--argjson disableIpDiscovery "${DISABLE_IP_DISCOVERY}" \
'{"ip": $ip, "port": $port, "securePort": $securePort, "cacheDir": $cacheDir, "webroot": $webroot, "presetDir": $presetDir, "disableIpDiscovery": $disableIpDiscovery}' \
> ${CONFIG_DIR}/settings.json